import Navbar from '@/Components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google';
import Footer from '@/Components/Footer';
import { useSession } from 'next-auth/react';
import Layout from '@/Components/Layout';



// import GlobalProvider from './GlobalProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tambari DUDS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">

     

  
       <div className=' App  flex flex-col gap-20 mb-10 '>
       
        
      <Layout>
      <body className={inter.className}>
        <Navbar/>
        
        <main className=' p-4 max-w-7xl m-auto min-w-[300px] overflow-hidden'>
       
       
        {children}

      
       
        </main>
        </body>

      </Layout>
  
       </div>

      <div className=' bg-yellow-800  p-2 rounded-3xl'>
      <Footer />
      </div>

    </html>
  )};
